steps:
  - id: 'tf init'
    name: 'gcr.io/${PROJECT_ID}/terraform'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
          for dir in environments/*/
          do
            cd ${dir}
            env=${dir%*/}
            env=${env#*/}
            echo ""
            echo "*************** TERRAFORM INIT ******************"
            echo "* Environment: ${env}"
            echo "*************************************************"
            terraform init -backend-config=bucket=${PROJECT_ID}_tf-state || exit 1
            cd ../../
          done
    env:
      - "TF_VAR_project=${PROJECT_ID}"

  - id: 'tf plan'
    name: 'gcr.io/${PROJECT_ID}/terraform'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
          for dir in environments/*/
          do
            cd ${dir}
            env=${dir%*/}
            env=${env#*/}
            echo ""
            echo "*************** TERRAFORM PLAN ******************"
            echo "* Environment: ${env}"
            echo "*************************************************"
            terraform plan -out terraform.tfplan || exit 1
            cd ../../
          done
    env:
      - "TF_VAR_project=${PROJECT_ID}"

  - id: 'tf apply'
    name: 'gcr.io/${PROJECT_ID}/terraform'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
          for dir in environments/*/
          do
            cd ${dir}
            env=${dir%*/}
            env=${env#*/}
            echo ""
            echo "*************** TERRAFORM APPLY ******************"
            echo "* Environment: ${env}"
            echo "*************************************************"
            terraform apply terraform.tfplan || exit 1
            cd ../../
          done
    env:
      - "TF_VAR_project=${PROJECT_ID}"
