export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

export ZSH="$HOME/.oh-my-zsh"

export TERM="screen-256color"

plugins=(
  git
  zsh-syntax-highlighting
  zsh-autosuggestions
  )

source $ZSH/oh-my-zsh.sh

# Aliases
source $HOME/.aliases

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND='rg --files --no-ignore-vcs --hidden'

# Terraform
export PATH="$PATH:${HOME}/.tfenv/bin"

# Golang (Development)
export GOPATH="${HOME}/.go"
export GOROOT="/usr/local/go"
export PATH="$PATH:${GOPATH}/bin:${GOROOT}/bin"

eval "$(starship init zsh)"
